###  Numpy is the fundamental package for scientific computing with Python. It contains among other things:

- A powerful N-dimentional array object 
- Sophiscated (broadcasting) functions 
- Tools for integrating C/C++ and Fortman code 
- Useful linear algebra, Fourier transform, and random number capabilities 

Source: https://numpy.org

In [1]:
# impoting the numpy liabrary
import numpy as np 

### If you got an error while running the above cell, import it by using the following command 

!pip3 install numpy 

In [3]:
# check the numpy library 
np.__version__

'1.21.5'

In [4]:
# create the numpy array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [5]:
[1,4,'2', 5, False]

[1, 4, '2', 5, False]

In [6]:
np.array([1,4,'2', 5, False])

array(['1', '4', '2', '5', 'False'], dtype='<U11')

In [7]:
[1,4, 5, False]

[1, 4, 5, False]

In [8]:
np.array([1,4, 5, False])

array([1, 4, 5, 0])

In [9]:
[False, True, 4, 6]

[False, True, 4, 6]

In [10]:
np.array([False, True, 4, 6])

array([0, 1, 4, 6])

### Difference b/w numpy array and list 

- Data type should be same of all the elements in a numpy array whereas it be different in case of lists 
- **Broadcasting**: https://numpy.org/doc/stable/user/basics.broadcasting.html
https://docs.scipy.org/doc//numpy-1.17.0/user/basics.broadcasting.html

In [11]:
# if we add an element of string data type in a numpy array whereas 
# then it will upcast the data type to string of all the elements.
np.array([1,4,2,'5',3,False])

array(['1', '4', '2', '5', '3', 'False'], dtype='<U11')

Now we will create one sample list and numpy array and  apply a very basic function of multiplication by 2. We will see that in case of list the elements are duplicated an appended to the list whereas in case of numpy array we got an array where all elements are multiplied by 2.

In [16]:
# create a sample list 
sample_list = [1,2,3,4,5,6]
print(sample_list)

[1, 2, 3, 4, 5, 6]


In [13]:
sample_list*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [17]:
sample_list*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [19]:
# create a numpy array 
sample_numpy_array = np.array([1,2,3,4,5,6])
sample_numpy_array

array([1, 2, 3, 4, 5, 6])

In [20]:
sample_numpy_array*2

array([ 2,  4,  6,  8, 10, 12])

In [22]:
sample_numpy_array/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

Create a matrix using numpy 

In [14]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [15]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
# MATRIX 
a = np.array(a)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[0][1]

2

In [27]:
a[0]

array([1, 2, 3])

In [28]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# Create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [34]:
# cerate another matrix 
np.random.randint(0,10,(3,3))

array([[3, 5, 0],
       [2, 3, 8],
       [1, 3, 3]])

We got a different matrix when we generated another random matrix: We can get the same matrix again by fixing the seed. Let's see how?

In [35]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [36]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [45]:
# fixing the random seed
np.random.seed(2)
np.random.randint(0,10,(3,3))

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5]])

In [47]:
# fixing the random seed
np.random.seed(2)
np.random.randint(0,10,(3,3))

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5]])

In [48]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [49]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [50]:
# fixing the random seed
np.random.seed()
np.random.randint(0,10,(3,3))

array([[8, 2, 2],
       [1, 9, 2],
       [5, 3, 6]])

In [51]:
# fixing the random seed
np.random.seed()
np.random.randint(0,10,(3,3))

array([[2, 1, 2],
       [8, 8, 5],
       [0, 3, 5]])

Create a matrix of Zeroes of specific dimension. 

In [53]:
# Create a 3x4 integer array filled with zeroes
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Create matrix of Ones of specific dimension.

In [54]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create a matrix with any specific number of specific dimension.

In [55]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

array concatenation

In [61]:
# concatenation in 2-d arrays 
matrix1 = np.array([[1,2,3],
                 [4,5,6]])
print("matrix1")
matrix1

matrix1


array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
matrix2 = np.array([[7,8,9],
                   [10,11,12]])
print('matrix2')
matrix2

matrix2


array([[ 7,  8,  9],
       [10, 11, 12]])

In [63]:
# concatinate along the first the axis 
matrix_1_2_combineRowWise = np.concatenate([matrix1, matrix2], axis=0)
print('Combined on Row (axis=0)')
matrix_1_2_combineRowWise

Combined on Row (axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Concatenate Columnwise

In [65]:
matrix_1_2_combineColumnWise = np.concatenate([matrix1, matrix2], axis=1)
print('Combined on Column (axis=1)')
matrix_1_2_combineColumnWise

Combined on Column (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])